# Generated by Django 6.0.2 on 2026-03-01 17:18

import django_providerkit.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderModel',
            fields=[
                ('name', models.CharField(help_text='Provider name (e.g., openai, scaleway)', max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
                ('display_name', models.CharField(help_text='Provider display name', verbose_name='Display Name')),
                ('description', models.CharField(help_text='Provider description', verbose_name='Description')),
                ('priority', models.IntegerField(help_text='Provider priority', verbose_name='Priority')),
                ('config_status_str', models.CharField(help_text='Config status', verbose_name='Config status')),
                ('config_prefix', models.CharField(help_text='Config prefix', verbose_name='Config prefix')),
                ('config_keys', models.JSONField(help_text='Config keys', verbose_name='Config keys')),
                ('missing_config_keys', models.JSONField(help_text='Missing config keys', verbose_name='Missing config keys')),
                ('is_config_ready', models.BooleanField(help_text='Is config ready', verbose_name='Is config ready')),
                ('package_status_str', models.CharField(help_text='Package status', verbose_name='Package status')),
                ('required_packages', models.JSONField(help_text='Required packages', verbose_name='Required packages')),
                ('missing_packages', models.JSONField(help_text='Missing packages', verbose_name='Missing packages')),
                ('are_packages_installed', models.BooleanField(help_text='Are packages installed', verbose_name='Are packages installed')),
                ('service_status_str', models.CharField(help_text='Service status', verbose_name='Service status')),
                ('missing_services', models.JSONField(help_text='Missing services', verbose_name='Missing services')),
                ('services', models.JSONField(help_text='Services', verbose_name='Services')),
                ('are_services_implemented', models.BooleanField(help_text='Are services implemented', verbose_name='Are services implemented')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['-priority', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(help_text='Instruction or prompt sent to the AI provider', verbose_name='Instruction')),
                ('conversation', models.TextField(help_text='Conversation with the AI provider', verbose_name='Conversation')),
                ('context', models.JSONField(help_text='Context sent to the AI provider', verbose_name='Context')),
                ('provider', django_providerkit.fields.ProviderField(blank=True, help_text='Select a provider', max_length=100, verbose_name='Provider')),
                ('model_name', models.CharField(help_text='Model used (e.g., gpt-4.1, mistral-small-3.2)', max_length=255, verbose_name='Model')),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Number of input tokens consumed', verbose_name='Input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Number of output tokens consumed', verbose_name='Output tokens')),
                ('response', models.JSONField(blank=True, default=dict, help_text='Response from the provider', verbose_name='Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Handle',
                'verbose_name_plural': 'Handles',
                'ordering': ['-created_at'],
            },
        ),
    ]
